version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_USER: guest
    networks:
      - poc-network

  producer:
    build: ./producer
    ports:
      - 8080:8080
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - poc-network

  processor:
    build: ./processor
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
    networks:
    - poc-network

  consumer:
    build: ./consumer
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - poc-network

networks:
  poc-network:
    external: true
