spring:
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    port: 5672

  cloud:
    stream:
      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true
      function:
        bindings:
          companyDomainReceived-in-0: input
      bindings:
        input:
          destination: notify-topic
          group: consumer
