spring:
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    port: 5672

  cloud:
    stream:
      bindings:
        onReceive-in-0:
          destination: uppercase-values-topic
          group: consumer
