spring:
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    port: 5672

  cloud:
    stream:
      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true
      function:
        bindings:
          validateUniqueDomain-in-0: input
          validateUniqueDomain-out-0: output
      bindings:
        input:
          destination: processor-topic
          group: processor
        output:
          destination: notify-topic
